In [11]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80,90,100])
b = np.array([[1., 1.],[1., 1.]])
c = np.array([1,2,3],dtype = 'int16')

print(a)
print(b)
print(c)
print('\n')
print(a.shape)
print(b.shape)
print(c.shape)
print('\n')
print(a.dtype)
print(b.dtype)
print(c.dtype)
print('\n')
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

[ 10  20  30  40  50  60  70  80  90 100]
[[1. 1.]
 [1. 1.]]
[1 2 3]


(10,)
(2, 2)
(3,)


int64
float64
int16


8
8
2


In [15]:
print(a.size * a.itemsize)
print(b.size * b.itemsize)
print(c.size * c.itemsize)

80
32
6
